INSERT INTO `location_countries` (`id`, `code`, `name`, `enabled`, `code_3`, `code_iso_numeric`) VALUES
(1, 'US', 'United States', 1, 'USA', '840'),
(2, 'CA', 'Canada', 1, 'CAN', '124'),
(3, 'AU', 'Australia', 1, 'AUS', '036'),
(4, 'FR', 'France', 0, 'FRA', '250'),
(5, 'DE', 'Germany', 0, 'DEU', '276'),
(6, 'IS', 'Iceland', 0, 'ISL', '352'),
(7, 'IE', 'Ireland', 0, 'IRL', '372'),
(8, 'IT', 'Italy', 0, 'ITA', '380'),
(9, 'ES', 'Spain', 0, 'ESP', '724'),
(10, 'SE', 'Sweden', 0, 'SWE', '752'),
(11, 'AT', 'Austria', 0, 'AUT', '040'),
(12, 'BE', 'Belgium', 0, 'BEL', '056'),
(13, 'FI', 'Finland', 0, 'FIN', '246'),
(14, 'CZ', 'Czech Republic', 0, 'CZE', '203'),
(15, 'DK', 'Denmark', 0, 'DNK', '208'),
(16, 'NO', 'Norway', 0, 'NOR', '578'),
(17, 'GB', 'United Kingdom', 0, 'GBR', '826'),
(18, 'CH', 'Switzerland', 0, 'CHE', '756'),
(19, 'NZ', 'New Zealand', 0, 'NZL', '554'),
(20, 'RU', 'Russian Federation', 0, 'RUS', '643'),
(21, 'PT', 'Portugal', 0, 'PRT', '620'),
(22, 'NL', 'Netherlands', 0, 'NLD', '528'),
(23, 'IM', 'Isle of Man', 0, 'IMN', '833'),
(24, 'AF', 'Afghanistan', 0, 'AFG', '004'),
(25, 'AX', 'Aland Islands ﻿ Åland Islands', 0, 'ALA', '248'),
(26, 'AL', 'Albania', 0, 'ALB', '008'),
(27, 'DZ', 'Algeria', 0, 'DZA', '012'),
(28, 'AS', 'American Samoa', 0, 'ASM', '016'),
(29, 'AD', 'Andorra', 0, 'AND', '020'),
(30, 'AO', 'Angola', 0, 'AGO', '024'),
(31, 'AI', 'Anguilla', 0, 'AIA', '660'),
(32, 'AQ', 'Antarctica', 0, 'ATA', '010'),
(33, 'AG', 'Antigua and Barbuda', 0, 'ATG', '028'),
(34, 'AR', 'Argentina', 0, 'ARG', '032'),
(35, 'AM', 'Armenia', 0, 'ARM', '051'),
(36, 'AW', 'Aruba', 0, 'ABW', '533'),
(37, 'AZ', 'Azerbaijan', 0, 'AZE', '031'),
(38, 'BS', 'Bahamas', 0, 'BHS', '044'),
(39, 'BH', 'Bahrain', 0, 'BHR', '048'),
(40, 'BD', 'Bangladesh', 0, 'BGD', '050'),
(41, 'BB', 'Barbados', 0, 'BRB', '052'),
(42, 'BY', 'Belarus', 0, 'BLR', '112'),
(43, 'BZ', 'Belize', 0, 'BLZ', '084'),
(44, 'BJ', 'Benin', 0, 'BEN', '204'),
(45, 'BM', 'Bermuda', 0, 'BMU', '060'),
(46, 'BT', 'Bhutan', 0, 'BTN', '064'),
(47, 'BO', 'Bolivia, Plurinational State of', 0, 'BOL', '068'),
(48, 'BA', 'Bosnia and Herzegovina', 0, 'BIH', '070'),
(49, 'BW', 'Botswana', 0, 'BWA', '072'),
(50, 'BV', 'Bouvet Island', 0, 'BVT', '074'),
(51, 'BR', 'Brazil', 0, 'BRA', '076'),
(52, 'IO', 'British Indian Ocean Territory', 0, 'IOT', '086'),
(53, 'BN', 'Brunei Darussalam', 0, 'BRN', '096'),
(54, 'BG', 'Bulgaria', 0, 'BGR', '100'),
(55, 'BF', 'Burkina Faso', 0, 'BFA', '854'),
(56, 'BI', 'Burundi', 0, 'BDI', '108'),
(57, 'KH', 'Cambodia', 0, 'KHM', '116'),
(58, 'CM', 'Cameroon', 0, 'CMR', '120'),
(59, 'CV', 'Cape Verde', 0, 'CPV', '132'),
(60, 'KY', 'Cayman Islands', 0, 'CYM', '136'),
(61, 'CF', 'Central African Republic', 0, 'CAF', '140'),
(62, 'TD', 'Chad', 0, 'TCD', '148'),
(63, 'CL', 'Chile', 0, 'CHL', '152'),
(64, 'CN', 'China', 0, 'CHN', '156'),
(65, 'CX', 'Christmas Island', 0, 'CXR', '162'),
(66, 'CC', 'Cocos (Keeling) Islands', 0, 'CCK', '166'),
(67, 'CO', 'Colombia', 0, 'COL', '170'),
(68, 'KM', 'Comoros', 0, 'COM', '174'),
(69, 'CG', 'Congo', 0, 'COG', '178'),
(70, 'CD', 'Congo, the Democratic Republic of the', 0, 'COD', '180'),
(71, 'CK', 'Cook Islands', 0, 'COK', '184'),
(72, 'CR', 'Costa Rica', 0, 'CRI', '188'),
(73, 'CI', 'Cote d''Ivoire', 0, 'CIV', '384'),
(74, 'HR', 'Croatia', 0, 'HRV', '191'),
(75, 'CU', 'Cuba', 0, 'CUB', '192'),
(76, 'CY', 'Cyprus', 0, 'CYP', '196'),
(77, 'DJ', 'Djibouti', 0, 'DJI', '262'),
(78, 'DM', 'Dominica', 0, 'DMA', '212'),
(79, 'DO', 'Dominican Republic', 0, 'DOM', '214'),
(80, 'EC', 'Ecuador', 0, 'ECU', '218'),
(81, 'EG', 'Egypt', 0, 'EGY', '818'),
(82, 'SV', 'El Salvador', 0, 'SLV', '222'),
(83, 'GQ', 'Equatorial Guinea', 0, 'GNQ', '226'),
(84, 'ER', 'Eritrea', 0, 'ERI', '232'),
(85, 'EE', 'Estonia', 0, 'EST', '233'),
(86, 'ET', 'Ethiopia', 0, 'ETH', '231'),
(87, 'FK', 'Falkland Islands (Malvinas)', 0, 'FLK', '238'),
(88, 'FO', 'Faroe Islands', 0, 'FRO', '234'),
(89, 'FJ', 'Fiji', 0, 'FJI', '242'),
(90, 'GF', 'French Guiana', 0, 'GUF', '254'),
(91, 'PF', 'French Polynesia', 0, 'PYF', '258'),
(92, 'TF', 'French Southern Territories', 0, 'ATF', '260'),
(93, 'GA', 'Gabon', 0, 'GAB', '266'),
(94, 'GM', 'Gambia', 0, 'GMB', '270'),
(95, 'GE', 'Georgia', 0, 'GEO', '268'),
(96, 'GH', 'Ghana', 0, 'GHA', '288'),
(97, 'GI', 'Gibraltar', 0, 'GIB', '292'),
(98, 'GR', 'Greece', 0, 'GRC', '300'),
(99, 'GL', 'Greenland', 0, 'GRL', '304'),
(100, 'GD', 'Grenada', 0, 'GRD', '308'),
(101, 'GP', 'Guadeloupe', 0, 'GLP', '312'),
(102, 'GU', 'Guam', 0, 'GUM', '316'),
(103, 'GT', 'Guatemala', 0, 'GTM', '320'),
(104, 'GG', 'Guernsey', 0, 'GGY', '831'),
(105, 'GN', 'Guinea', 0, 'GIN', '324'),
(106, 'GW', 'Guinea-Bissau', 0, 'GNB', '624'),
(107, 'GY', 'Guyana', 0, 'GUY', '328'),
(108, 'HT', 'Haiti', 0, 'HTI', '332'),
(109, 'HM', 'Heard Island and McDonald Islands', 0, 'HMD', '334'),
(110, 'VA', 'Holy See (Vatican City State)', 0, 'VAT', '336'),
(111, 'HN', 'Honduras', 0, 'HND', '340'),
(112, 'HK', 'Hong Kong', 0, 'HKG', '344'),
(113, 'HU', 'Hungary', 0, 'HUN', '348'),
(114, 'IN', 'India', 0, 'IND', '356'),
(115, 'ID', 'Indonesia', 0, 'IDN', '360'),
(116, 'IR', 'Iran, Islamic Republic of', 0, 'IRN', '364'),
(117, 'IQ', 'Iraq', 0, 'IRQ', '368'),
(118, 'IL', 'Israel', 0, 'ISR', '376'),
(119, 'JM', 'Jamaica', 0, 'JAM', '388'),
(120, 'JP', 'Japan', 0, 'JPN', '392'),
(121, 'JE', 'Jersey', 0, 'JEY', '832'),
(122, 'JO', 'Jordan', 0, 'JOR', '400'),
(123, 'KZ', 'Kazakhstan', 0, 'KAZ', '398'),
(124, 'KE', 'Kenya', 0, 'KEN', '404'),
(125, 'KI', 'Kiribati', 0, 'KIR', '296'),
(126, 'KP', 'Korea, Democratic People''s Republic of', 0, 'PRK', '408'),
(127, 'KR', 'Korea, Republic of', 0, 'KOR', '410'),
(128, 'KW', 'Kuwait', 0, 'KWT', '414'),
(129, 'KG', 'Kyrgyzstan', 0, 'KGZ', '417'),
(130, 'LA', 'Lao People''s Democratic Republic', 0, 'LAO', '418'),
(131, 'LV', 'Latvia', 0, 'LVA', '428'),
(132, 'LB', 'Lebanon', 0, 'LBN', '422'),
(133, 'LS', 'Lesotho', 0, 'LSO', '426'),
(134, 'LR', 'Liberia', 0, 'LBR', '430'),
(135, 'LY', 'Libyan Arab Jamahiriya', 0, 'LBY', '434'),
(136, 'LI', 'Liechtenstein', 0, 'LIE', '438'),
(137, 'LT', 'Lithuania', 0, 'LTU', '440'),
(138, 'LU', 'Luxembourg', 0, 'LUX', '442'),
(139, 'MO', 'Macao', 0, 'MAC', '446'),
(140, 'MK', 'Macedonia', 0, 'MKD', '807'),
(141, 'MG', 'Madagascar', 0, 'MDG', '450'),
(142, 'MW', 'Malawi', 0, 'MWI', '454'),
(143, 'MY', 'Malaysia', 0, 'MYS', '458'),
(144, 'MV', 'Maldives', 0, 'MDV', '462'),
(145, 'ML', 'Mali', 0, 'MLI', '466'),
(146, 'MT', 'Malta', 0, 'MLT', '470'),
(147, 'MH', 'Marshall Islands', 0, 'MHL', '584'),
(148, 'MQ', 'Martinique', 0, 'MTQ', '474'),
(149, 'MR', 'Mauritania', 0, 'MRT', '478'),
(150, 'MU', 'Mauritius', 0, 'MUS', '480'),
(151, 'YT', 'Mayotte', 0, 'MYT', '175'),
(152, 'MX', 'Mexico', 0, 'MEX', '484'),
(153, 'FM', 'Micronesia, Federated States of', 0, 'FSM', '583'),
(154, 'MD', 'Moldova, Republic of', 0, 'MDA', '498'),
(155, 'MC', 'Monaco', 0, 'MCO', '492'),
(156, 'MN', 'Mongolia', 0, 'MNG', '496'),
(157, 'ME', 'Montenegro', 0, 'MNE', '499'),
(158, 'MS', 'Montserrat', 0, 'MSR', '500'),
(159, 'MA', 'Morocco', 0, 'MAR', '504'),
(160, 'MZ', 'Mozambique', 0, 'MOZ', '508'),
(161, 'MM', 'Myanmar', 0, 'MMR', '104'),
(162, 'NA', 'Namibia', 0, 'NAM', '516'),
(163, 'NR', 'Nauru', 0, 'NRU', '520'),
(164, 'NP', 'Nepal', 0, 'NPL', '524'),
(165, 'AN', 'Netherlands Antilles', 0, 'ANT', '530'),
(166, 'NC', 'New Caledonia', 0, 'NCL', '540'),
(167, 'NI', 'Nicaragua', 0, 'NIC', '558'),
(168, 'NE', 'Niger', 0, 'NER', '562'),
(169, 'NG', 'Nigeria', 0, 'NGA', '566'),
(170, 'NU', 'Niue', 0, 'NIU', '570'),
(171, 'NF', 'Norfolk Island', 0, 'NFK', '574'),
(172, 'MP', 'Northern Mariana Islands', 0, 'MNP', '580'),
(173, 'OM', 'Oman', 0, 'OMN', '512'),
(174, 'PK', 'Pakistan', 0, 'PAK', '586'),
(175, 'PW', 'Palau', 0, 'PLW', '585'),
(176, 'PS', 'Palestinian Territory, Occupied', 0, 'PSE', '275'),
(177, 'PA', 'Panama', 0, 'PAN', '591'),
(178, 'PG', 'Papua New Guinea', 0, 'PNG', '598'),
(179, 'PY', 'Paraguay', 0, 'PRY', '600'),
(180, 'PE', 'Peru', 0, 'PER', '604'),
(181, 'PH', 'Philippines', 0, 'PHL', '608'),
(182, 'PN', 'Pitcairn', 0, 'PCN', '612'),
(183, 'PL', 'Poland', 0, 'POL', '616'),
(184, 'PR', 'Puerto Rico', 0, 'PRI', '630'),
(185, 'QA', 'Qatar', 0, 'QAT', '634'),
(186, 'RE', 'Reunion', 0, 'REU', '638'),
(187, 'RO', 'Romania', 0, 'ROU', '642'),
(188, 'RW', 'Rwanda', 0, 'RWA', '646'),
(189, 'BL', 'Saint Barthélemy', 0, 'BLM', '652'),
(190, 'SH', 'Saint Helena', 0, 'SHN', '654'),
(191, 'KN', 'Saint Kitts and Nevis', 0, 'KNA', '659'),
(192, 'LC', 'Saint Lucia', 0, 'LCA', '662'),
(193, 'MF', 'Saint Martin (French part)', 0, 'MAF', '663'),
(194, 'PM', 'Saint Pierre and Miquelon', 0, 'SPM', '666'),
(195, 'VC', 'Saint Vincent and the Grenadines', 0, 'VCT', '670'),
(196, 'WS', 'Samoa', 0, 'WSM', '882'),
(197, 'SM', 'San Marino', 0, 'SMR', '674'),
(198, 'ST', 'Sao Tome and Principe', 0, 'STP', '678'),
(199, 'SA', 'Saudi Arabia', 0, 'SAU', '682'),
(200, 'SN', 'Senegal', 0, 'SEN', '686'),
(201, 'RS', 'Serbia', 0, 'SRB', '688'),
(202, 'SC', 'Seychelles', 0, 'SYC', '690'),
(203, 'SL', 'Sierra Leone', 0, 'SLE', '694'),
(204, 'SG', 'Singapore', 0, 'SGP', '702'),
(205, 'SK', 'Slovakia', 0, 'SVK', '703'),
(206, 'SI', 'Slovenia', 0, 'SVN', '705'),
(207, 'SB', 'Solomon Islands', 0, 'SLB', '090'),
(208, 'SO', 'Somalia', 0, 'SOM', '706'),
(209, 'ZA', 'South Africa', 0, 'ZAF', '710'),
(210, 'GS', 'South Georgia and the South Sandwich Islands', 0, 'SGS', '239'),
(211, 'LK', 'Sri Lanka', 0, 'LKA', '144'),
(212, 'SD', 'Sudan', 0, 'SDN', '736'),
(213, 'SR', 'Suriname', 0, 'SUR', '740'),
(214, 'SJ', 'Svalbard and Jan Mayen', 0, 'SJM', '744'),
(215, 'SZ', 'Swaziland', 0, 'SWZ', '748'),
(216, 'SY', 'Syrian Arab Republic', 0, 'SYR', '760'),
(217, 'TW', 'Taiwan, Province of China', 0, 'TWN', '158'),
(218, 'TJ', 'Tajikistan', 0, 'TJK', '762'),
(219, 'TZ', 'Tanzania, United Republic of', 0, 'TZA', '834'),
(220, 'TH', 'Thailand', 0, 'THA', '764'),
(221, 'TL', 'Timor-Leste', 0, 'TLS', '626'),
(222, 'TG', 'Togo', 0, 'TGO', '768'),
(223, 'TK', 'Tokelau', 0, 'TKL', '772'),
(224, 'TO', 'Tonga', 0, 'TON', '776'),
(225, 'TT', 'Trinidad and Tobago', 0, 'TTO', '780'),
(226, 'TN', 'Tunisia', 0, 'TUN', '788'),
(227, 'TR', 'Turkey', 0, 'TUR', '792'),
(228, 'TM', 'Turkmenistan', 0, 'TKM', '795'),
(229, 'TC', 'Turks and Caicos Islands', 0, 'TCA', '796'),
(230, 'TV', 'Tuvalu', 0, 'TUV', '798'),
(231, 'UG', 'Uganda', 0, 'UGA', '800'),
(232, 'UA', 'Ukraine', 0, 'UKR', '804'),
(233, 'AE', 'United Arab Emirates', 0, 'ARE', '784'),
(234, 'UM', 'United States Minor Outlying Islands', 0, 'UMI', '581'),
(235, 'UY', 'Uruguay', 0, 'URY', '858'),
(236, 'UZ', 'Uzbekistan', 0, 'UZB', '860'),
(237, 'VU', 'Vanuatu', 0, 'VUT', '548'),
(238, 'VE', 'Venezuela, Bolivarian Republic of', 0, 'VEN', '862'),
(239, 'VN', 'Viet Nam', 0, 'VNM', '704'),
(240, 'VG', 'Virgin Islands, British', 0, 'VGB', '092'),
(241, 'VI', 'Virgin Islands, U.S.', 0, 'VIR', '850'),
(242, 'WF', 'Wallis and Futuna', 0, 'WLF', '876'),
(243, 'EH', 'Western Sahara', 0, 'ESH', '732'),
(244, 'YE', 'Yemen', 0, 'YEM', '887'),
(245, 'ZM', 'Zambia', 0, 'ZMB', '894'),
(246, 'ZW', 'Zimbabwe', 0, 'ZWE', '716');

CREATE TABLE IF NOT EXISTS `location_states` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_id` int(11) DEFAULT NULL,
  `code` varchar(50) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,  
  PRIMARY KEY (`id`),
  KEY `country_id` (`country_id`),
  KEY `name` (`name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `location_states` (`country_id`, `code`, `name`) VALUES
(1, 'AL', 'Alabama'),
(1, 'AK', 'Alaska'),
(1, 'AS', 'American Samoa'),
(1, 'AZ', 'Arizona'),
(1, 'AR', 'Arkansas'),
(1, 'CA', 'California'),
(1, 'CO', 'Colorado'),
(1, 'CT', 'Connecticut'),
(1, 'DE', 'Delaware'),
(1, 'DC', 'Dist. of Columbia'),
(1, 'FL', 'Florida'),
(1, 'GA', 'Georgia'),
(1, 'GU', 'Guam'),
(1, 'HI', 'Hawaii'),
(1, 'ID', 'Idaho'),
(1, 'IL', 'Illinois'),
(1, 'IN', 'Indiana'),
(1, 'IA', 'Iowa'),
(1, 'KS', 'Kansas'),
(1, 'KY', 'Kentucky'),
(1, 'LA', 'Louisiana'),
(1, 'ME', 'Maine'),
(1, 'MD', 'Maryland'),
(1, 'MH', 'Marshall Islands'),
(1, 'MA', 'Massachusetts'),
(1, 'MI', 'Michigan'),
(1, 'FM', 'Micronesia'),
(1, 'MN', 'Minnesota'),
(1, 'MS', 'Mississippi'),
(1, 'MO', 'Missouri'),
(1, 'MT', 'Montana'),
(1, 'NE', 'Nebraska'),
(1, 'NV', 'Nevada'),
(1, 'NH', 'New Hampshire'),
(1, 'NJ', 'New Jersey'),
(1, 'NM', 'New Mexico'),
(1, 'NY', 'New York'),
(1, 'NC', 'North Carolina'),
(1, 'ND', 'North Dakota'),
(1, 'MP', 'Northern Marianas'),
(1, 'OH', 'Ohio'),
(1, 'OK', 'Oklahoma'),
(1, 'OR', 'Oregon'),
(1, 'PW', 'Palau'),
(1, 'PA', 'Pennsylvania'),
(1, 'PR', 'Puerto Rico'),
(1, 'RI', 'Rhode Island'),
(1, 'SC', 'South Carolina'),
(1, 'SD', 'South Dakota'),
(1, 'TN', 'Tennessee'),
(1, 'TX', 'Texas'),
(1, 'UT', 'Utah'),
(1, 'VT', 'Vermont'),
(1, 'VA', 'Virginia'),
(1, 'VI', 'Virgin Islands'),
(1, 'WA', 'Washington'),
(1, 'WV', 'West Virginia'),
(1, 'WI', 'Wisconsin'),
(1, 'WY', 'Wyoming'),
(2, 'AB', 'Alberta'),
(2, 'BC', 'British Columbia'),
(2, 'MB', 'Manitoba'),
(2, 'NB', 'New Brunswick'),
(2, 'NL', 'Newfoundland and Labrador'),
(2, 'NT', 'Northwest Territories'),
(2, 'NS', 'Nova Scotia'),
(2, 'NU', 'Nunavut'),
(2, 'ON', 'Ontario'),
(2, 'PE', 'Prince Edward Island'),
(2, 'QC', 'Quebec'),
(2, 'SK', 'Saskatchewan'),
(2, 'YT', 'Yukon'),
(3, 'NSW', 'New South Wales'),
(3, 'QLD', 'Queensland'),
(3, 'SA', 'South Australia'),
(3, 'TAS', 'Tasmania'),
(3, 'VIC', 'Victoria'),
(3, 'WA', 'Western Australia'),
(3, 'NT', 'Northern Territory'),
(3, 'ACT', 'Australian Capital Territory'),
(5, 'BW', 'Baden-Württemberg'),
(5, 'BY', 'Bavaria'),
(5, 'BE', 'Berlin'),
(5, 'BB', 'Brandenburg'),
(5, 'HB', 'Bremen'),
(5, 'HH', 'Hamburg'),
(5, 'HE', 'Hesse'),
(5, 'MV', 'Mecklenburg-Vorpommern'),
(5, 'NI', 'Lower Saxony'),
(5, 'NW', 'North Rhine-Westphalia'),
(5, 'RP', 'Rhineland-Palatinate'),
(5, 'SL', 'Saarland'),
(5, 'SN', 'Saxony'),
(5, 'ST', 'Saxony-Anhalt'),
(5, 'SH', 'Schleswig-Holstein'),
(5, 'TH', 'Thuringia'),
(7, 'D', 'Dublin'),
(7, 'WW', 'Wicklow'),
(7, 'WX', 'Wexford'),
(7, 'CW', 'Carlow'),
(7, 'KE', 'Kildare'),
(7, 'MH', 'Meath'),
(7, 'LH', 'Louth'),
(7, 'MN', 'Monaghan'),
(7, 'CN', 'Cavan'),
(7, 'LD', 'Longford'),
(7, 'WH', 'Westmeath'),
(7, 'OY', 'Offaly'),
(7, 'LS', 'Laois'),
(7, 'KK', 'Kilkenny'),
(7, 'WD', 'Waterford'),
(7, 'C', 'Cork'),
(7, 'KY', 'Kerry'),
(7, 'LK', 'Limerick'),
(7, 'TN', 'North Tipperary'),
(7, 'TS', 'South Tipperary'),
(7, 'CE', 'Clare'),
(7, 'G', 'Galway'),
(7, 'MO', 'Mayo'),
(7, 'RN', 'Roscommon'),
(7, 'SO', 'Sligo'),
(7, 'LM', 'Leitrim'),
(7, 'DL', 'Donegal'),
(8, 'abruzzo', 'Abruzzo'),
(8, 'aosta_valley', 'Aosta Valley'),
(8, 'apulia', 'Apulia'),
(8, 'basilicata', 'Basilicata'),
(8, 'calabria', 'Calabria'),
(8, 'campania', 'Campania'),
(8, 'emilia_romagna', 'Emilia-Romagna'),
(8, 'friuli_venezia_giulia', 'Friuli-VeneziaGiulia'),
(8, 'lazio', 'Lazio'),
(8, 'liguria', 'Liguria'),
(8, 'lombardy', 'Lombardy'),
(8, 'marche', 'Marche'),
(8, 'molise', 'Molise'),
(8, 'piedmont', 'Piedmont'),
(8, 'sardinia', 'Sardinia'),
(8, 'sicily', 'Sicily'),
(8, 'tuscany', 'Tuscany'),
(8, 'trentino_alto_adige', 'Trentino-Alto Adige'),
(8, 'umbria', 'Umbria'),
(10, 'stockholm', 'Stockholm County'),
(10, 'skåne', 'Skåne County'),
(10, 'uppsala', 'Uppsala County'),
(10, 'västmanland', 'Västmanland County'),
(10, 'örebro', 'Örebro County'),
(10, 'jönköping', 'Jönköping County'),
(10, 'östergötland', 'Östergötland County'),
(10, 'västerbotten', 'Västerbotten County'),
(10, 'gävleborg', 'Gävleborg County'),
(10, 'västra_götaland', 'Västra Götaland County'),
(10, 'södermanland', 'Södermanland County'),
(10, 'värmland', 'Värmland County'),
(10, 'halland', 'Halland County'),
(10, 'kronoberg', 'Kronoberg County'),
(11, 'burgenland', 'Burgenland'),
(11, 'carinthia', 'Carinthia'),
(11, 'lower_austria', 'Lower Austria'),
(11, 'upper_austria', 'Upper Austria'),
(11, 'salzburg', 'Salzburg'),
(11, 'styria', 'Styria'),
(11, 'tyrol', 'Tyrol'),
(11, 'vorarlberg', 'Vorarlberg'),
(11, 'vienna', 'Vienna'),
(14, 'PRAGUE', 'Prague'),
(14, 'ST', 'Central Bohemian'),
(14, 'JC', 'South Bohemian '),
(14, 'PL', 'Plzeň'),
(14, 'KA', 'Karlovy Vary'),
(14, 'US', 'Ústí nad Labem'),
(14, 'LI', 'Liberec'),
(14, 'KR', 'Hradec Králové'),
(14, 'PA', 'Pardubice'),
(14, 'OL', 'Olomouc'),
(14, 'MO', 'Moravian-Silesian'),
(14, 'JM', 'South Moravian'),
(14, 'ZL', 'Zlín'),
(14, 'VY', 'Vysočina'),
(16, 'finnmark', 'Northern Norway/Finnmark'),
(16, 'troms', 'Northern Norway/Troms'),
(16, 'nordland', 'Northern Norway/Nordland'),
(16, 'nord_trøndelag', 'Trøndelag/Nord-Trøndelag'),
(16, 'sør_trøndelag', 'Trøndelag/Sør-Trøndelag'),
(16, 'møre_og_romsdal', 'Western Norway/Møre og Romsdal'),
(16, 'sogn_og_fjordane', 'Western Norway/Sogn og Fjordane'),
(16, 'hordaland', 'Western Norway/Hordaland'),
(16, 'rogaland', 'Western Norway/Rogaland'),
(16, 'vest_agder', 'Southern Norway/Vest-Agder'),
(16, 'aust_agder', 'Southern Norway/Aust-Agder'),
(16, 'telemark', 'Eastern Norway/Telemark'),
(16, 'buskerud', 'Eastern Norway/Buskerud'),
(16, 'hedmark', 'Eastern Norway/Hedmark'),
(16, 'oppland', 'Eastern Norway/Oppland'),
(16, 'akershus', 'Eastern Norway/Akershus'),
(16, 'oslo', 'Eastern Norway/Oslo'),
(16, 'vestfold', 'Eastern Norway/Vestfold'),
(16, 'østfold', 'Eastern Norway/Østfold'),
(17, 'england_avon', 'England/Avon'),
(17, 'england_bedfordshire', 'England/Bedfordshire'),
(17, 'england_berkshire', 'England/Berkshire'),
(17, 'england_buckinghamshire', 'England/Buckinghamshire'),
(17, 'england_cambridgeshire', 'England/Cambridgeshire'),
(17, 'england_cheshire', 'England/Cheshire'),
(17, 'england_cleveland', 'England/Cleveland'),
(17, 'england_cornwall', 'England/Cornwall'),
(17, 'england_cumbria', 'England/Cumbria'),
(17, 'england_derbyshire', 'England/Derbyshire'),
(17, 'england_devon', 'England/Devon'),
(17, 'england_dorset', 'England/Dorset'),
(17, 'england_durham', 'England/Durham'),
(17, 'england_east_sussex', 'England/East Sussex'),
(17, 'england_essex', 'England/Essex'),
(17, 'england_gloucestershire', 'England/Gloucestershire'),
(17, 'england_hampshire', 'England/Hampshire'),
(17, 'england_herefordshire', 'England/Herefordshire'),
(17, 'england_hertfordshire', 'England/Hertfordshire'),
(17, 'england_isle_of_wight', 'England/Isle of Wight'),
(17, 'england_kent', 'England/Kent'),
(17, 'england_lancashire', 'England/Lancashire'),
(17, 'england_leicestershire', 'England/Leicestershire'),
(17, 'england_lincolnshire', 'England/Lincolnshire'),
(17, 'england_london', 'England/London'),
(17, 'england_merseyside', 'England/Merseyside'),
(17, 'england_middlesex', 'England/Middlesex'),
(17, 'england_norfolk', 'England/Norfolk'),
(17, 'england_northamptonshire', 'England/Northamptonshire'),
(17, 'england_northumberland', 'England/Northumberland'),
(17, 'england_north_humberside', 'England/North Humberside'),
(17, 'england_north_yorkshire', 'England/North Yorkshire'),
(17, 'england_nottinghamshire', 'England/Nottinghamshire'),
(17, 'england_oxfordshire', 'England/Oxfordshire'),
(17, 'england_rutland', 'England/Rutland'),
(17, 'england_shropshire', 'England/Shropshire'),
(17, 'england_somerset', 'England/Somerset'),
(17, 'england_south_humberside', 'England/South Humberside'),
(17, 'england_south_yorkshire', 'England/South Yorkshire'),
(17, 'england_staffordshire', 'England/Staffordshire'),
(17, 'england_suffolk', 'England/Suffolk'),
(17, 'england_surrey', 'England/Surrey'),
(17, 'england_tyne_and_wear', 'England/Tyne and Wear'),
(17, 'england_warwickshire', 'England/Warwickshire'),
(17, 'england_west_midlands', 'England/West Midlands'),
(17, 'england_west_sussex', 'England/West Sussex'),
(17, 'england_west_yorkshire', 'England/West Yorkshire'),
(17, 'england_wiltshire', 'England/Wiltshire'),
(17, 'england_worcestershire', 'England/Worcestershire'),
(17, 'wales_clwyd', 'Wales/Clwyd'),
(17, 'wales_dyfed', 'Wales/Dyfed'),
(17, 'wales_gwent', 'Wales/Gwent'),
(17, 'wales_gwynedd', 'Wales/Gwynedd'),
(17, 'wales_mid_glamorgan', 'Wales/Mid Glamorgan'),
(17, 'wales_powys', 'Wales/Powys'),
(17, 'wales_south_glamorgan', 'Wales/South Glamorgan'),
(17, 'wales_west_glamorgan', 'Wales/West Glamorgan'),
(17, 'scotland_aberdeenshire', 'Scotland/Aberdeenshire'),
(17, 'scotland_angus', 'Scotland/Angus'),
(17, 'scotland_argyll', 'Scotland/Argyll'),
(17, 'scotland_ayrshire', 'Scotland/Ayrshire'),
(17, 'scotland_banffshire', 'Scotland/Banffshire'),
(17, 'scotland_berwickshire', 'Scotland/Berwickshire'),
(17, 'scotland_bute', 'Scotland/Bute'),
(17, 'scotland_caithness', 'Scotland/Caithness'),
(17, 'scotland_clackmannanshire', 'Scotland/Clackmannanshire'),
(17, 'scotland_dumfriesshire', 'Scotland/Dumfriesshire'),
(17, 'scotland_dunbartonshire', 'Scotland/Dunbartonshire'),
(17, 'scotland_east_lothian', 'Scotland/East Lothian'),
(17, 'scotland_fife', 'Scotland/Fife'),
(17, 'scotland_inverness-shire', 'Scotland/Inverness-shire'),
(17, 'scotland_kincardineshire', 'Scotland/Kincardineshire'),
(17, 'scotland_kinross-shire', 'Scotland/Kinross-shire'),
(17, 'scotland_kirkcudbrightshire', 'Scotland/Kirkcudbrightshire'),
(17, 'scotland_lanarkshire', 'Scotland/Lanarkshire'),
(17, 'scotland_midlothian', 'Scotland/Midlothian'),
(17, 'scotland_moray', 'Scotland/Moray'),
(17, 'scotland_nairnshire', 'Scotland/Nairnshire'),
(17, 'scotland_orkney', 'Scotland/Orkney'),
(17, 'scotland_peeblesshire', 'Scotland/Peeblesshire'),
(17, 'scotland_perthshire', 'Scotland/Perthshire'),
(17, 'scotland_renfrewshire', 'Scotland/Renfrewshire'),
(17, 'scotland_ross-shire', 'Scotland/Ross-shire'),
(17, 'scotland_roxburghshire', 'Scotland/Roxburghshire'),
(17, 'scotland_selkirkshire', 'Scotland/Selkirkshire'),
(17, 'scotland_shetland', 'Scotland/Shetland'),
(17, 'scotland_stirlingshire', 'Scotland/Stirlingshire'),
(17, 'scotland_sutherland', 'Scotland/Sutherland'),
(17, 'scotland_west_lothian', 'Scotland/West Lothian'),
(17, 'scotland_wigtownshire', 'Scotland/Wigtownshire'),
(17, 'northern_ireland_antrim', 'Northern Ireland/Antrim'),
(17, 'northern_ireland_armagh', 'Northern Ireland/Armagh'),
(17, 'northern_ireland_down', 'Northern Ireland/Down'),
(17, 'northern_ireland_fermanagh', 'Northern Ireland/Fermanagh'),
(17, 'northern_ireland_londonderry', 'Northern Ireland/Londonderry'),
(17, 'northern_ireland_tyrone', 'Northern Ireland/Tyrone'),
(19, 'northland', 'Northland'),
(19, 'auckland', 'Auckland'),
(19, 'waikato', 'Waikato'),
(19, 'bay_of_plenty', 'Bay of Plenty'),
(19, 'east_cape', 'East Cape'),
(19, 'hawkes_bay', 'Hawke''s Bay'),
(19, 'taranaki', 'Taranaki'),
(19, 'manawatu-wanganui', 'Manawatu-Wanganui'),
(19, 'wellington', 'Wellington'),
(19, 'tasman', 'Tasman'),
(19, 'nelson', 'Nelson'),
(19, 'marlborough', 'Marlborough'),
(19, 'west_coast', 'West Coast'),
(19, 'canterbury', 'Canterbury'),
(19, 'otago', 'Otago'),
(19, 'southland', 'Southland'),
(20, 'amur', 'Amur'),
(20, 'arkhangelsk', 'Arkhangelsk'),
(20, 'astrakhan', 'Astrakhan'),
(20, 'belgorod', 'Belgorod'),
(20, 'bryansk', 'Bryansk'),
(20, 'chelyabinsk', 'Chelyabinsk'),
(20, 'chita', 'Chita'),
(20, 'irkutsk', 'Irkutsk'),
(20, 'ivanovo', 'Ivanovo'),
(20, 'kaliningrad', 'Kaliningrad'),
(20, 'kaluga', 'Kaluga'),
(20, 'kemerovo', 'Kemerovo'),
(20, 'kirov', 'Kirov'),
(20, 'kostroma', 'Kostroma'),
(20, 'kurgan', 'Kurgan'),
(20, 'kursk', 'Kursk'),
(20, 'leningrad', 'Leningrad'),
(20, 'lipetsk', 'Lipetsk'),
(20, 'magadan', 'Magadan'),
(20, 'moscow', 'Moscow'),
(20, 'murmansk', 'Murmansk'),
(20, 'nizhny_novgorod', 'Nizhny Novgorod'),
(20, 'novgorod', 'Novgorod'),
(20, 'novosibirsk', 'Novosibirsk'),
(20, 'omsk', 'Omsk'),
(20, 'orenburg', 'Orenburg'),
(20, 'oryol', 'Oryol'),
(20, 'penza', 'Penza'),
(20, 'pskov', 'Pskov'),
(20, 'rostov', 'Rostov'),
(20, 'ryazan', 'Ryazan'),
(20, 'sakhalin', 'Sakhalin'),
(20, 'samara', 'Samara'),
(20, 'saratov', 'Saratov'),
(20, 'smolensk', 'Smolensk'),
(20, 'sverdlovsk', 'Sverdlovsk'),
(20, 'tambov', 'Tambov'),
(20, 'tomsk', 'Tomsk'),
(20, 'tver', 'Tver'),
(20, 'tula', 'Tula'),
(20, 'tyumen', 'Tyumen'),
(20, 'ulyanovsk', 'Ulyanovsk'),
(20, 'vladimir', 'Vladimir'),
(20, 'volgograd', 'Volgograd'),
(20, 'vologda', 'Vologda'),
(20, 'voronezh', 'Voronezh'),
(20, 'yaroslavl', 'Yaroslavl'),
(21, 'lisbon', 'Lisbon'),
(21, 'leiria', 'Leiria'),
(21, 'santarém', 'Santarém'),
(21, 'setúbal', 'Setúbal'),
(21, 'beja', 'Beja'),
(21, 'faro', 'Faro'),
(21, 'évora', 'Évora'),
(21, 'portalegre', 'Portalegre'),
(21, 'castelo_branco', 'Castelo Branco'),
(21, 'guarda', 'Guarda'),
(21, 'coimbra', 'Coimbra'),
(21, 'aveiro', 'Aveiro'),
(21, 'viseu', 'Viseu'),
(21, 'bragança', 'Bragança'),
(21, 'vila_real', 'Vila Real'),
(21, 'porto', 'Porto'),
(21, 'braga', 'Braga'),
(21, 'viana_do_castelo', 'Viana do Castelo'),
(22, 'drenthe', 'Drenthe'),
(22, 'flevoland', 'Flevoland'),
(22, 'frisia', 'Frisia'),
(22, 'gelderland', 'Gelderland'),
(22, 'groningen', 'Groningen'),
(22, 'limburg', 'Limburg'),
(22, 'north brabant', 'North Brabant'),
(22, 'north holland', 'North Holland'),
(22, 'overijssel', 'Overijssel'),
(22, 'utrecht', 'Utrecht'),
(22, 'zealand', 'Zealand'),
(22, 'south holland', 'South Holland'),
(51, 'AC', 'Acre'),
(51, 'AL', 'Alagoas'),
(51, 'AP', 'Amapá'),
(51, 'AM', 'Amazonas'),
(51, 'BA', 'Bahia'),
(51, 'CE', 'Ceará'),
(51, 'DF', 'Distrito Federal'),
(51, 'ES', 'Espírito Santo'),
(51, 'GO', 'Goiás'),
(51, 'MA', 'Maranhão'),
(51, 'MT', 'Mato Grosso'),
(51, 'MS', 'Mato Grosso do Sul'),
(51, 'MG', 'Minas Gerais'),
(51, 'PA', 'Pará'),
(51, 'PB', 'Paraíba'),
(51, 'PR', 'Paraná'),
(51, 'PE', 'Pernambuco'),
(51, 'PI', 'Piauí'),
(51, 'RJ', 'Rio de Janeiro'),
(51, 'RN', 'Rio Grande do Norte'),
(51, 'RS', 'Rio Grande do Sul'),
(51, 'RO', 'Rondônia'),
(51, 'RR', 'Roraima'),
(51, 'SC', 'Santa Catarina'),
(51, 'SP', 'São Paulo'),
(51, 'SE', 'Sergipe'),
(51, 'TO', 'Tocantins'),
(17, 'england_greater_manchester', 'England/Greater Manchester'),
(15, 'CAPITAL', 'Capital'),
(15, 'CENTRAL', 'Central Denmark'),
(15, 'NORTH-DENMARK', 'North Denmark '),
(15, 'ZEALAND', 'Zealand'),
(15, 'SOUTHERN-DENMARK', 'Southern Denmark');
